name: "SolutionsStoreApp"
capabilities:
  - camera
  - non_motorola_device
  - motorola_browser
extensions:
  - json
  - rexml
  - set
  - activesupport
app_type: "rhoelements"
bbver: "4.6"
wp:
  productid: "aba07d00-704a-012f-ca32-00216aab8fda"
wm:
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
android:
  version: "2.3.3"
build: "debug"
applog: "rholog.txt"
version: "1.0"
symbian:
  uid: "0xe6142d7c"
sdkversion: "3.4.0"
vendor: "rhomobile"
iphone:
  provisionprofile: D7102EF2-33D7-4007-841B-F4CF6F703A60
  BundleURLScheme: "solutionsstoreapp"
  BundleIdentifier: "com.rhomobile.solutionsstoreapp"
  sdk: "iphonesimulator5.1"
  codesignidentity: "iPhone Developer: Derek Warren (Z8283W4V6Q)"
  entitlements: ""
  configuration: "Release"
  #emulatortarget: "ipad"
