sdkversion: "3.5.0"
name: "SolutionsStoreApp"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "4.6"
applog: "rholog.txt"
iphone:
  provisionprofile: "D7102EF2-33D7-4007-841B-F4CF6F703A60"
  BundleURLScheme: "solutionsstoreapp"
  BundleIdentifier: "com.rhomobile.solutionsstoreapp"
  codesignidentity: "iPhone Developer: Derek Warren (Z8283W4V6Q)"
#sdk: "iphonesimulator5.1"
  entitlements: 
  configuration: "Release"
wp:
#emulatortarget: "ipad"
  productid: "c88a18f0-1fb1-0130-f15d-00216aab8fda"
symbian:
  uid: "0xe23a96c7"
android:
  version: "2.3.3"
extensions:
  - json
  - rexml
  - set
  - activesupport
  - barcode
app_type: "rhoelements"
capabilities:
  - camera
  - non_motorola_device
  - motorola_browser
